### PR TITLE
Adding a hands-on tutorial 

### PR DESCRIPTION
**Pull request by charifmahmoudi**
As discussed, this hands-on tutorial shows how to get started with node.wot

### CODE REVIEW

**Comment by danielpeintner** [comment]
Thanks @charifmahmoudi 

You need to sign first the "Eclipse Contributor Agreement" (https://www.eclipse.org/legal/ECA.php) before we can accept any PR.
Can you please do so...

**Comment by charifmahmoudi** [comment]
the ECA seems to be ok on the eclipse website, however, it is not reflected here (see attached screenshot)
any idea how to fix that ? it needs just some time ?
image

**Comment by danielpeintner** [comment]
I believe that your github account is not linked to the Eclipse credentials.

I think the email addresses need to match...

**Comment by danielpeintner** [comment]
@charifmahmoudi I started the validation process again and the github account seems still not be properly linked with your ECA

**Pull request closed without merging**
