### PR TITLE
Html updates

### PR DESCRIPTION
**Pull request by danielpeintner**
- adds meta-name description and author
- fixes HTML syntax

### CODE REVIEW

**Comment by danielpeintner** [comment]
Besides the XML Syntax the *important* change is a proper description for search engines

```
<meta name="description" content="Eclipse Thingweb node-wot project - Web of Things (WoT) implementation based on Node.js" />
<meta name="author" content="Eclipse Thingweb node-wot team" />
```

**Comment by danielpeintner** [comment]
@sebastiankb @egekorkan @wiresio @relu91 
Any objections before I merge?

**Comment by relu91** [comment]
Not sure if mentioning IoT in the description increases somehow the visibility of the website also for searches that are not strictly wot related. Like (taken from our website):
> Eclipse Thingweb node-wot project - Web of Things (WoT) implementation based on Node.js. The Web of Things (WoT) and node-wot provide a set of standardized technology building blocks that help to simplify IoT application development by following the well-known and successful Web paradigm.

**Comment by danielpeintner** [comment]
There are recommendations saying the description should be between 50 and 160 characters. (see https://moz.com/learn/seo/meta-description)

The current text

> Eclipse Thingweb node-wot project - Web of Things (WoT) implementation based on Node.js

has 87 characters.

Once I try to extend it gets to large , e.g., see below 196 characters

> Eclipse Thingweb node-wot project - Web of Things (WoT) implementation based on Node.js. WoT and node-wot provide standardized technology building blocks that simplify IoT application development.

Any proposals to improve / change?

**Comment by relu91** [comment]
Ah I see, tried to make it shorter but I don't have a strong preference (you may use the first version as well):
> Eclipse Thingweb node-wot - NodeJS Web of Things (WoT) implementation. WoT provides standardized technology building blocks for IoT application development.

**Comment by egekorkan** [comment]
I think both @danielpeintner and @relu91 approaches are fine. Just that `NodeJS` should be `Node.js`. Here is my proposal that is like the inverse of @relu91 but after some head scratches to get into 160 character length.

>  Web of Things (WoT) proposes building blocks for development of IoT applications. Eclipse Thingweb node-wot provides Node.js packages for WoT implementations.

This is 158 characters. Ideally it should be `for the development`

**Comment by danielpeintner** [comment]
Eclipse Thingweb node-wot provides Node.js packages for Web of Things (WoT) implementations which are standardized building blocks for IoT applications.

153

**Pull request merged**
