### PR TITLE
reduce header banner and footer width

### PR DESCRIPTION
**Pull request by danielpeintner**

### CODE REVIEW

**Comment by danielpeintner** [comment]
@sebastiankb @egekorkan @wiresio  does this update make sense ?

For your convenience find screenshots that show a reduced resolution by 50%. The header banner and the footer are now limited in size and do no stretch anylonger the full width.

grafik

grafik

**Comment by egekorkan** [comment]
I like it definitely more :)

**Comment by sebastiankb** [comment]
+1 

I'm wondering if we can also place the new WoT video

**Comment by danielpeintner** [comment]
> +1

Okay to merge?

> I'm wondering if we can also place the new WoT video

sure, but that is unrelated to this change.. I can do that right after...

**Review by sebastiankb — APPROVED** [review]

**Pull request merged**
